### ISSUE TITLE
Feature: User can view a calendar of all scheduled events

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a personal calendar of all of their scheduled events. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view their calendar of events. They can click on events in the menu to get to the page as well. The clicked on day on the calendar will display if there are any events. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue1m](https://user-images.githubusercontent.com/106547566/200648208-efe24e96-116c-4a5c-99d7-2fcc22d52250.PNG)
![fpissue1d](https://user-images.githubusercontent.com/106547566/200648310-2927be29-ed55-4a45-a8ad-3b24b6fa00b7.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to create table for users, events, and locations
- [x] Update `data.sql` to take sample data and insert it into each of the tables

### ☁️ Server Tasks

- [x] Update `server/index.js` to get user data from events table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display the nav bar (when signed in)
- [x]  Create a component to display the calendar page
- [x]  Create a component to display the calendar
- [x] Create a component to display tiles
- [x]  Set up for hashrouting

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
