### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create their own account with a chosen username and password.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create a new account by clicking on the register link in the nav bar or on the login page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue12m](https://user-images.githubusercontent.com/106547566/200666274-22efb0b2-6bed-412b-a5a8-ca32574c4e4f.PNG)
![fpissue12d](https://user-images.githubusercontent.com/106547566/200666279-0ccc1e6e-f7c3-4bf1-907d-f076f2cf19b9.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to hash passwords then insert username and hashed password into the database 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display registration page
- [x] Fetch request on submit to post entered user data
- [x] Change nav bar menu items when on log in page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
