### ISSUE TITLE
Feature: User can login to an account

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can login to their account using their username and password to see all saved event and outfit entries.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can login to their account by clicking on the login link in the nav bar or the link on the registration page and login using their created username and password. They will then be able to see all of their saved data.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue13m](https://user-images.githubusercontent.com/106547566/200666709-e4caa460-fc9d-4787-8466-fde40e47a9aa.PNG)
![fpissue13d](https://user-images.githubusercontent.com/106547566/200666714-5cd1c70e-3c0b-4469-a68d-855d870b8019.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a post request for sign-in
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the sign-in page;
- [x] Update component to authorize the user.
- [x] Let user sign out by clicking the log out link.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
