### ISSUE TITLE
Feature: User can create a new entry for an event

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a new entry for a competition/practice which will be added to the calendar.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the "New+" button which will pull up a page for the user to entered more detailed information about the event. Once submitted, the event will be added to the calendar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue4m](https://user-images.githubusercontent.com/106547566/200653283-1c928018-eb88-4fcd-984c-4ec210d011b0.PNG)
![fpissue4d](https://user-images.githubusercontent.com/106547566/200653287-8f73647f-e977-4c9e-bb59-b755da1d6e29.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to post event info to database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the event form.
- [x] Update "New+" button to go to the "Create Event" page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
