### ISSUE TITLE
Feature: User can edit an entry

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit all previously added information in their entry.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the "edit" button when viewing details for an entry in order to edit information. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue5m](https://user-images.githubusercontent.com/106547566/200653753-1360dde5-c349-473d-9691-451569acff0a.PNG)
![fpissue5d](https://user-images.githubusercontent.com/106547566/200653756-8a81b563-6d9f-47ce-89eb-9c009023c9f7.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a put request for the data at the eventId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the edit event page
- [x] Update event-form component to take props from clicked event.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
