### ISSUE TITLE
Feature: User can delete an entry

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an entry to remove it from their calendar. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the "delete entry" button while editing an event in order to permanently remove it from their calendar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue6m](https://user-images.githubusercontent.com/106547566/200654166-34f906ae-ad03-4232-8c7e-e87bdde5b578.PNG)
![fpissue6d](https://user-images.githubusercontent.com/106547566/200654170-beb90280-b024-4bf4-9fea-5cac6c730f5e.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to delete an event by the eventId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update a component to display delete modal when clicking on the delete event button
- [x] Update component to show delete button when editing an event
- [x] Update a component to hide delete modal when clicking on the cancel button in the modal
- [x] Update a component to send a fetch request to delete the current event and then return to the events page when clicking on the delete button in the modal

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
