### ISSUE TITLE
Feature: User can view a list of all saved outfits

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all of their outfits in a list. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view outfits by clicking on "outfits" in the nav bar. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue7m](https://user-images.githubusercontent.com/106547566/200655105-b7af9751-f875-43c8-89f0-9a9fffce78f6.PNG)
![fpissue7d](https://user-images.githubusercontent.com/106547566/200655106-3640e1dd-18a6-4a2d-8909-cd92df456b13.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to have more than one outfit to test

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a get request for all outfits for the current user
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display tiles for outfits the user has saved.
- [x] Update component to display the outfits page when clicking on the outfits link

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
