### ISSUE TITLE
Feature: User can create a new outfit

### ISSUE THREAD

**Issue by arieldonner** [arieldonner/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a new saved outfit with given details.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the "New+" button on the outfits page in order to create a new saved outfit. User can fill in details for each outfit.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![fpissue8m](https://user-images.githubusercontent.com/106547566/200660830-06490539-c41f-4ec7-8636-30845e8612ad.PNG)
![fpissue8d](https://user-images.githubusercontent.com/106547566/200660832-a582faf9-9f6f-43a5-ab4e-846b66b98081.PNG)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a post request to create a new outfit
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for the create-outfit page
- [x] Update component to send a fetch request when submitting to post entered info to database for outfits.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
